CREATE TABLE users (
    id VARCHAR(36) PRIMARY KEY,
    username VARCHAR(25) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    role ENUM('HR', 'Vendor') NOT NULL,
    email VARCHAR(100) UNIQUE NULL,
    company_name VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL
);