name: Build and deploy to server
on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Install Azure CLI
        run: |
          Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile AzureCLI.msi
          Start-Process msiexec.exe -ArgumentList '/i AzureCLI.msi /quiet /norestart' -NoNewWindow -Wait
        shell: pwsh

      - name: Login to Azure
        run: |
          az login --service-principal `
            --username ${{ secrets.AZURE_CLIENT_ID }} `
            --password ${{ secrets.AZURE_CLIENT_SECRET }} `
            --tenant ${{ secrets.AZURE_TENANT_ID }}
        shell: pwsh

      - name: Copy migration files
        run: xcopy /i migrations build\migrations

      - name: Build
        run: go build -o build/event-management-app.exe -v

      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: event-management-system-adi
          slot-name: 'Production'
          package: build/
          publish-profile: ${{ secrets.AZURE_APP_PUBLISH_PROFILE_PROD }}
