name: Build and deploy to server

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Copy migration files
        run: xcopy /i migrations build\migrations

      - name: Build
        run: go build -o build/event-management-app.exe -v

      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: event-management-system-adi
          package: build/
          publish-profile: ${{ secrets.AZURE_APP_PUBLISH_PROFILE_PROD }}
